### ISSUE TITLE
QUIC spam protection vs INITIAL packet spam

### ISSUE THREAD

**Issue by nbridge-jump** [firedancer-io/firedancer#1947] opened 2024-05-24 16:58 UTC
INITIAL packets have to be decrypted before they can be processed. So we need to rate limit them to avoid DoS issues.

May need a tester regardless, to verify the rate limit is effective.

**Comment by mmcgee-jump** [comment] 2024-07-29 20:45
Duplicate of #1376

**Closed by mmcgee-jump** 2024-07-29 20:45 UTC
Labels: quic, Priority: Medium
