### ISSUE TITLE
fdctl fails for some users

### ISSUE THREAD

**Issue by nbridge-jump** [firedancer-io/firedancer#1436] opened 2024-04-02 20:45 UTC
fdctl was failing for me on a node. Turns out this was because my gid was not equal to my uid.

Also, it seems to assume users are configured in /etc/passwd, but this is not necessarily true.

**Comment by mmcgee-jump** [comment] 2024-04-02 20:53
Dupe of #1398

**Closed by mmcgee-jump** 2024-04-02 20:53 UTC
